name: Build MinimalOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo libisl-dev nasm gcc make

      - name: Modify Makefile to use i686-elf-gcc
        run: |
          # Replace i386-elf with i686-elf in all Makefiles
          find . -name "Makefile" -type f -exec sed -i 's/i386-elf-/i686-elf-/g' {} \;
          # Show the changes
          grep -r "i686-elf" --include="Makefile" .

      - name: Set up cross-compiler
        run: |
          # Download and install cross compiler
          wget https://github.com/lordmilko/i686-elf-tools/releases/download/7.1.0/i686-elf-tools-linux.zip
          unzip i686-elf-tools-linux.zip

          # Add to PATH
          echo "$PWD/i686-elf-tools-linux/bin" >> $GITHUB_PATH
          export PATH=$PATH:$PWD/i686-elf-tools-linux/bin

          # Verify installation
          ls -la $PWD/i686-elf-tools-linux/bin
          i686-elf-gcc --version || echo "i686-elf-gcc not found"

      - name: Build MinimalOS
        run: |
          # Print PATH for debugging
          echo "PATH=$PATH"
          # List tools in i686 directory
          ls -la $PWD/i686-elf-tools-linux/bin/
          # Try to find gcc
          which i686-elf-gcc || echo "i686-elf-gcc not in PATH"
          # Build with environment variables explicitly set
          export PATH=$PATH:$PWD/i686-elf-tools-linux/bin
          make
          make usb

      - name: Upload OS image
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
        with:
          name: minimalos-image
          path: minimalos.img
