name: Build MinimalOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo libisl-dev nasm gcc make

      - name: Set up cross-compiler
        run: |
          wget https://github.com/lordmilko/i686-elf-tools/releases/download/7.1.0/i686-elf-tools-linux.zip
          unzip i686-elf-tools-linux.zip
          echo "$PWD/i686-elf-tools-linux/bin" >> $GITHUB_PATH

      - name: Build MinimalOS
        run: |
          make
          make usb

      - name: Upload OS image
        uses: actions/upload-artifact@v3
        with:
          name: minimalos-image
          path: minimalos.img
