name: Build MinimalOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo libisl-dev nasm gcc make

      - name: Set up cross-compiler
        run: |
          # Download and install i686-elf cross compiler
          wget https://github.com/lordmilko/i686-elf-tools/releases/download/7.1.0/i686-elf-tools-linux.zip
          unzip i686-elf-tools-linux.zip

          # Add to PATH and create symlink for i386-elf-gcc
          export PATH=$PATH:$PWD/i686-elf-tools-linux/bin
          echo "$PWD/i686-elf-tools-linux/bin" >> $GITHUB_PATH

          # Create symlinks for i386-elf-* tools pointing to i686-elf-* tools
          sudo mkdir -p /usr/local/bin
          for tool in gcc ld objcopy objdump; do
            sudo ln -sf $PWD/i686-elf-tools-linux/bin/i686-elf-$tool /usr/local/bin/i386-elf-$tool
          done

          # Verify the symlinks are working
          ls -la /usr/local/bin/i386-elf-*
          which i386-elf-gcc || echo "i386-elf-gcc not found in path"

      - name: Build MinimalOS
        run: |
          # Display environment for debugging
          echo "PATH=$PATH"
          make
          make usb

      - name: Upload OS image
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
        with:
          name: minimalos-image
          path: minimalos.img
